"""Bakes the game's own Ore UI pieces into the app.

Minecraft's menus are HTML rendered by Gameface, so the real look comes from
nine-slice border-image PNGs plus the Minecraft fonts. Both are tiny.
"""
import base64, io, json, os, shutil
from PIL import Image, ImageFilter, ImageEnhance

HBUI = r"C:\XboxGames\Minecraft for Windows\Content\data\gui\dist\hbui"
UI   = r"C:\XboxGames\Minecraft for Windows\Content\data\resource_packs\vanilla\textures\ui"
ASSETS = os.path.join(HBUI, "assets")
FONTS  = os.path.join(HBUI, "fonts")
OUT_JS = os.path.join("src", "uiassets.js")
OUT_FONTS = os.path.join("src", "fonts")

# name in the app -> file prefix in the game's asset folder
SLICES = {
  "btn_primary.png":        "pressable_primary_default-",
  "btn_primary_hover.png":  "pressable_primary_hovered-",
  "btn_primary_press.png":  "pressable_primary_pressed-",
  "btn_secondary.png":      "pressable_secondary_default-",
  "btn_secondary_hover.png":"pressable_secondary_hovered-",
  "btn_secondary_press.png":"pressable_secondary_pressed-",
  "card.png":               "detailed-card-7c80",
  "card_action.png":        "detailed-card-action_default-",
  "card_action_hover.png":  "detailed-card-action_hovered-",
  "card_action_press.png":  "detailed-card-action_pressed-",
  "pencil_btn.png":         "detailed-card-additional-action_default-",
  "pencil_btn_hover.png":   "detailed-card-additional-action_hovered-",
  "pencil_btn_press.png":   "detailed-card-additional-action_pressed-",
  "field.png":              "baseTextField_neutral80-",
}

def find(prefix, folder=ASSETS):
    for f in sorted(os.listdir(folder)):
        if f.startswith(prefix):
            return os.path.join(folder, f)
    raise SystemExit("missing asset: " + prefix)

assets = {}
def put(name, data, mime):
    assets[name] = {"type": mime, "base64": base64.b64encode(data).decode()}
    print(f"  {name:<24} {len(data):>7} bytes")

print("nine-slice pieces:")
for name, prefix in SLICES.items():
    with open(find(prefix), "rb") as f:
        put(name, f.read(), "image/png")

print("icons:")
with open(os.path.join(UI, "pencil_edit_icon.png"), "rb") as f:
    put("pencil.png", f.read(), "image/png")
buf = io.BytesIO()
Image.open(os.path.join(UI, "World.png")).convert("RGBA").save(buf, "PNG")
put("world.png", buf.getvalue(), "image/png")

print("backdrop:")
pan = Image.open(os.path.join(UI, "panorama_0.png")).convert("RGB")
pan = pan.resize((640, 360), Image.LANCZOS).filter(ImageFilter.GaussianBlur(9))
pan = ImageEnhance.Brightness(pan).enhance(0.38)
pan = ImageEnhance.Color(pan).enhance(0.6)
buf = io.BytesIO()
pan.save(buf, "JPEG", quality=72, optimize=True)
put("bg.jpg", buf.getvalue(), "image/jpeg")

with open(OUT_JS, "w", encoding="utf-8") as f:
    f.write("// Generated by build-oreui.py from the installed game files.\n")
    f.write("module.exports = " + json.dumps(assets, indent=2) + ";\n")
print("wrote", OUT_JS, os.path.getsize(OUT_JS), "bytes")

# the real menu fonts, replacing Monocraft
for old in os.listdir(OUT_FONTS):
    os.remove(os.path.join(OUT_FONTS, old))
for out, prefix in [("MinecraftSeven.otf", "Minecraft-Seven-6"),
                    ("MinecraftTen.otf",   "Minecraft-Ten-")]:
    src = find(prefix, FONTS)
    shutil.copy(src, os.path.join(OUT_FONTS, out))
    print(f"  font {out:<22} {os.path.getsize(src):>7} bytes")
