"""Bakes the app's own assets into the exe: the logo and the interface clicks.

Everything else the app draws is CSS, so there is nothing else to carry.
"""
import base64, io, json, math, os, random, struct, wave

LOGO = r"C:\Users\BUNNY\Downloads\ChatGPT Image Sep 2, 2026, 09_50_00 AM.png"
OUT = os.path.join("src", "uiassets.js")
RATE = 22050

from PIL import Image

assets = {}
def put(name, data, mime):
    assets[name] = {"type": mime, "base64": base64.b64encode(data).decode()}
    print(f"  {name:<14} {len(data):>7} bytes")

im = Image.open(LOGO).convert("RGBA")
for name, size in [("logo.png", 88), ("logo_big.png", 256)]:
    buf = io.BytesIO()
    im.resize((size, size), Image.LANCZOS).save(buf, "PNG", optimize=True)
    put(name, buf.getvalue(), "image/png")

def click(freq, ms, seed, gain):
    random.seed(seed)
    n = int(RATE * ms / 1000)
    frames = bytearray()
    for i in range(n):
        t = i / RATE
        env = math.exp(-t * 110.0)
        v = (math.sin(2 * math.pi * freq * t)
             + 0.3 * math.sin(2 * math.pi * freq * 2.03 * t)
             + 0.25 * (random.random() * 2 - 1) * math.exp(-t * 480.0)) * env * gain
        frames += struct.pack("<h", max(-32767, min(32767, int(v * 32767))))
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(RATE)
        w.writeframes(bytes(frames))
    return buf.getvalue()

put("click.wav", click(1150.0, 38, 7, 0.30), "audio/wav")
put("back.wav", click(680.0, 40, 11, 0.26), "audio/wav")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by build-assets.py.\n")
    f.write("module.exports = " + json.dumps(assets, indent=2) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
