"""Bakes a few real Minecraft UI textures into the app.

The panorama is the menu backdrop; blurred and darkened it becomes the app
background without carrying a megabyte of sky around.
"""
import base64, io, json, os
from PIL import Image, ImageFilter, ImageEnhance

GAME = r"C:\XboxGames\Minecraft for Windows\Content\data\resource_packs\vanilla\textures"
UI = os.path.join(GAME, "ui")
OUT = os.path.join("src", "uiassets.js")

assets = {}

def put(name, img, fmt, **kw):
    buf = io.BytesIO()
    img.save(buf, fmt, **kw)
    assets[name] = {"type": "image/png" if fmt == "PNG" else "image/jpeg",
                    "base64": base64.b64encode(buf.getvalue()).decode()}
    print(f"  {name:<12} {img.size!s:<12} {len(buf.getvalue()):>7} bytes")

# the pencil the Play screen actually uses
put("pencil.png", Image.open(os.path.join(UI, "pencil_edit_icon.png")).convert("RGBA"), "PNG")

# fallback thumbnail for a world with no saved icon
put("world.png", Image.open(os.path.join(UI, "World.png")).convert("RGBA"), "PNG")

# menu backdrop: one panorama face, small, blurred and dimmed
pan = Image.open(os.path.join(UI, "panorama_0.png")).convert("RGB")
pan = pan.resize((640, 360), Image.LANCZOS).filter(ImageFilter.GaussianBlur(9))
pan = ImageEnhance.Brightness(pan).enhance(0.34)
pan = ImageEnhance.Color(pan).enhance(0.55)
put("bg.jpg", pan, "JPEG", quality=72, optimize=True)

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by build-uiassets.py from the installed game files.\n")
    f.write("module.exports = " + json.dumps(assets, indent=2) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
